# Generated by Django 5.2.17 on 2026-08-17 16:42

import apps.ticketing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.ticketing.models.generate_ticket_code, editable=False, max_length=32, unique=True)),
                ('holder_name', models.CharField(max_length=150)),
                ('pdf_key', models.CharField(blank=True, max_length=300)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.reservation')),
            ],
            options={
                'ordering': ['issued_at'],
                'indexes': [models.Index(fields=['reservation'], name='ticketing_t_reserva_7ac678_idx')],
            },
        ),
    ]
