# Generated by Django 5.2.17 on 2026-08-12 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('doors_open_at', models.DateTimeField(blank=True, null=True)),
                ('sales_open_at', models.DateTimeField()),
                ('sales_close_at', models.DateTimeField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('has_seating', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['is_published', 'starts_at'], name='events_even_is_publ_415ff6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='BGN', max_length=3)),
                ('quantity_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_available', models.PositiveIntegerField()),
                ('max_per_order', models.PositiveSmallIntegerField(default=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'price_minor'],
                'constraints': [models.UniqueConstraint(fields=('event', 'name'), name='uniq_ticket_type_per_event'), models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_total'))), name='available_not_above_total')],
            },
        ),
    ]
